/* Automatically generated by tools/make_darwin_syscalls; DO NOT EDIT! */

static NTSTATUS darwin_NtReadFile( HANDLE a1, HANDLE a2, PIO_APC_ROUTINE a3, PVOID a4, PIO_STATUS_BLOCK a5, PVOID a6, ULONG a7, PLARGE_INTEGER a8, ULONG_PTR a9 )
{
    return NtReadFile( a1, a2, a3, a4, a5, a6, a7, a8, (PULONG)a9 );
}

static NTSTATUS darwin_NtDeviceIoControlFile( HANDLE a1, HANDLE a2, PIO_APC_ROUTINE a3, PVOID a4, PIO_STATUS_BLOCK a5, ULONG a6, PVOID a7, ULONG a8, ULONG_PTR a9, ULONG_PTR a10 )
{
    return NtDeviceIoControlFile( a1, a2, a3, a4, a5, a6, a7, a8, (PVOID)a9, (ULONG)a10 );
}

static NTSTATUS darwin_NtWriteFile( HANDLE a1, HANDLE a2, PIO_APC_ROUTINE a3, PVOID a4, PIO_STATUS_BLOCK a5, const void* a6, ULONG a7, PLARGE_INTEGER a8, ULONG_PTR a9 )
{
    return NtWriteFile( a1, a2, a3, a4, a5, a6, a7, a8, (PULONG)a9 );
}

static NTSTATUS darwin_NtWriteFileGather( HANDLE a1, HANDLE a2, PIO_APC_ROUTINE a3, PVOID a4, PIO_STATUS_BLOCK a5, FILE_SEGMENT_ELEMENT* a6, ULONG a7, PLARGE_INTEGER a8, ULONG_PTR a9 )
{
    return NtWriteFileGather( a1, a2, a3, a4, a5, a6, a7, a8, (PULONG)a9 );
}

static NTSTATUS darwin_NtMapViewOfSection( HANDLE a1, HANDLE a2, PVOID* a3, ULONG_PTR a4, SIZE_T a5, const LARGE_INTEGER* a6, SIZE_T* a7, SECTION_INHERIT a8, ULONG_PTR a9, ULONG_PTR a10 )
{
    return NtMapViewOfSection( a1, a2, a3, a4, a5, a6, a7, a8, (ULONG)a9, (ULONG)a10 );
}

static NTSTATUS darwin_NtAccessCheckAndAuditAlarm( UNICODE_STRING* a1, HANDLE a2, UNICODE_STRING* a3, UNICODE_STRING* a4, PSECURITY_DESCRIPTOR a5, ACCESS_MASK a6, GENERIC_MAPPING* a7, BOOLEAN a8, ULONG_PTR a9, ULONG_PTR a10, ULONG_PTR a11 )
{
    return NtAccessCheckAndAuditAlarm( a1, a2, a3, a4, a5, a6, a7, a8, (ACCESS_MASK*)a9, (NTSTATUS*)a10, (BOOLEAN*)a11 );
}

static NTSTATUS darwin_NtReadFileScatter( HANDLE a1, HANDLE a2, PIO_APC_ROUTINE a3, PVOID a4, PIO_STATUS_BLOCK a5, FILE_SEGMENT_ELEMENT* a6, ULONG a7, PLARGE_INTEGER a8, ULONG_PTR a9 )
{
    return NtReadFileScatter( a1, a2, a3, a4, a5, a6, a7, a8, (PULONG)a9 );
}

static NTSTATUS darwin_NtQueryDirectoryFile( HANDLE a1, HANDLE a2, PIO_APC_ROUTINE a3, PVOID a4, PIO_STATUS_BLOCK a5, PVOID a6, ULONG a7, FILE_INFORMATION_CLASS a8, ULONG_PTR a9, ULONG_PTR a10, ULONG_PTR a11 )
{
    return NtQueryDirectoryFile( a1, a2, a3, a4, a5, a6, a7, a8, (BOOLEAN)a9, (PUNICODE_STRING)a10, (BOOLEAN)a11 );
}

static NTSTATUS darwin_NtFsControlFile( HANDLE a1, HANDLE a2, PIO_APC_ROUTINE a3, PVOID a4, PIO_STATUS_BLOCK a5, ULONG a6, PVOID a7, ULONG a8, ULONG_PTR a9, ULONG_PTR a10 )
{
    return NtFsControlFile( a1, a2, a3, a4, a5, a6, a7, a8, (PVOID)a9, (ULONG)a10 );
}

static NTSTATUS darwin_NtCreateFile( PHANDLE a1, ACCESS_MASK a2, POBJECT_ATTRIBUTES a3, PIO_STATUS_BLOCK a4, PLARGE_INTEGER a5, ULONG a6, ULONG a7, ULONG a8, ULONG_PTR a9, ULONG_PTR a10, ULONG_PTR a11 )
{
    return NtCreateFile( a1, a2, a3, a4, a5, a6, a7, a8, (ULONG)a9, (PVOID)a10, (ULONG)a11 );
}

static NTSTATUS darwin_NtAccessCheckByTypeAndAuditAlarm( UNICODE_STRING* a1, HANDLE a2, UNICODE_STRING* a3, UNICODE_STRING* a4, PSECURITY_DESCRIPTOR a5, PSID a6, ACCESS_MASK a7, AUDIT_EVENT_TYPE a8, ULONG_PTR a9, ULONG_PTR a10, ULONG_PTR a11, ULONG_PTR a12, ULONG_PTR a13, ULONG_PTR a14, ULONG_PTR a15, ULONG_PTR a16 )
{
    return NtAccessCheckByTypeAndAuditAlarm( a1, a2, a3, a4, a5, a6, a7, a8, (ULONG)a9, (OBJECT_TYPE_LIST*)a10, (ULONG)a11, (GENERIC_MAPPING*)a12, (BOOLEAN)a13, (ACCESS_MASK*)a14, (NTSTATUS*)a15, (BOOLEAN*)a16 );
}

static NTSTATUS darwin_NtCreateLowBoxToken( HANDLE* a1, HANDLE a2, ACCESS_MASK a3, OBJECT_ATTRIBUTES* a4, SID* a5, ULONG a6, SID_AND_ATTRIBUTES* a7, ULONG a8, ULONG_PTR a9 )
{
    return NtCreateLowBoxToken( a1, a2, a3, a4, a5, a6, a7, a8, (HANDLE*)a9 );
}

static NTSTATUS darwin_NtCreateNamedPipeFile( PHANDLE a1, ULONG a2, POBJECT_ATTRIBUTES a3, PIO_STATUS_BLOCK a4, ULONG a5, ULONG a6, ULONG a7, ULONG a8, ULONG_PTR a9, ULONG_PTR a10, ULONG_PTR a11, ULONG_PTR a12, ULONG_PTR a13, ULONG_PTR a14 )
{
    return NtCreateNamedPipeFile( a1, a2, a3, a4, a5, a6, a7, a8, (ULONG)a9, (ULONG)a10, (ULONG)a11, (ULONG)a12, (ULONG)a13, (PLARGE_INTEGER)a14 );
}

static NTSTATUS darwin_NtCreateSectionEx( HANDLE* a1, ACCESS_MASK a2, const OBJECT_ATTRIBUTES* a3, const LARGE_INTEGER* a4, ULONG a5, ULONG a6, HANDLE a7, MEM_EXTENDED_PARAMETER* a8, ULONG_PTR a9 )
{
    return NtCreateSectionEx( a1, a2, a3, a4, a5, a6, a7, a8, (ULONG)a9 );
}

static NTSTATUS darwin_NtCreateThreadEx( HANDLE* a1, ACCESS_MASK a2, OBJECT_ATTRIBUTES* a3, HANDLE a4, PRTL_THREAD_START_ROUTINE a5, void* a6, ULONG a7, ULONG_PTR a8, ULONG_PTR a9, ULONG_PTR a10, ULONG_PTR a11 )
{
    return NtCreateThreadEx( a1, a2, a3, a4, a5, a6, a7, a8, (SIZE_T)a9, (SIZE_T)a10, (PS_ATTRIBUTE_LIST*)a11 );
}

static NTSTATUS darwin_NtCreateToken( PHANDLE a1, ACCESS_MASK a2, POBJECT_ATTRIBUTES a3, TOKEN_TYPE a4, PLUID a5, PLARGE_INTEGER a6, PTOKEN_USER a7, PTOKEN_GROUPS a8, ULONG_PTR a9, ULONG_PTR a10, ULONG_PTR a11, ULONG_PTR a12, ULONG_PTR a13 )
{
    return NtCreateToken( a1, a2, a3, a4, a5, a6, a7, a8, (PTOKEN_PRIVILEGES)a9, (PTOKEN_OWNER)a10, (PTOKEN_PRIMARY_GROUP)a11, (PTOKEN_DEFAULT_DACL)a12, (PTOKEN_SOURCE)a13 );
}

static NTSTATUS darwin_NtCreateTransaction( PHANDLE a1, ACCESS_MASK a2, POBJECT_ATTRIBUTES a3, LPGUID a4, HANDLE a5, ULONG a6, ULONG a7, ULONG a8, ULONG_PTR a9, ULONG_PTR a10 )
{
    return NtCreateTransaction( a1, a2, a3, a4, a5, a6, a7, a8, (PLARGE_INTEGER)a9, (PUNICODE_STRING)a10 );
}

static NTSTATUS darwin_NtCreateUserProcess( HANDLE* a1, HANDLE* a2, ACCESS_MASK a3, ACCESS_MASK a4, OBJECT_ATTRIBUTES* a5, OBJECT_ATTRIBUTES* a6, ULONG a7, ULONG a8, ULONG_PTR a9, ULONG_PTR a10, ULONG_PTR a11 )
{
    return NtCreateUserProcess( a1, a2, a3, a4, a5, a6, a7, a8, (RTL_USER_PROCESS_PARAMETERS*)a9, (PS_CREATE_INFO*)a10, (PS_ATTRIBUTE_LIST*)a11 );
}

static NTSTATUS darwin_NtLockFile( HANDLE a1, HANDLE a2, PIO_APC_ROUTINE a3, void* a4, PIO_STATUS_BLOCK a5, PLARGE_INTEGER a6, PLARGE_INTEGER a7, ULONG* a8, ULONG_PTR a9, ULONG_PTR a10 )
{
    return NtLockFile( a1, a2, a3, a4, a5, a6, a7, a8, (BOOLEAN)a9, (BOOLEAN)a10 );
}

static NTSTATUS darwin_NtMapViewOfSectionEx( HANDLE a1, HANDLE a2, PVOID* a3, const LARGE_INTEGER* a4, SIZE_T* a5, ULONG a6, ULONG a7, MEM_EXTENDED_PARAMETER* a8, ULONG_PTR a9 )
{
    return NtMapViewOfSectionEx( a1, a2, a3, a4, a5, a6, a7, a8, (ULONG)a9 );
}

static NTSTATUS darwin_NtNotifyChangeDirectoryFile( HANDLE a1, HANDLE a2, PIO_APC_ROUTINE a3, PVOID a4, PIO_STATUS_BLOCK a5, PVOID a6, ULONG a7, ULONG a8, ULONG_PTR a9 )
{
    return NtNotifyChangeDirectoryFile( a1, a2, a3, a4, a5, a6, a7, a8, (BOOLEAN)a9 );
}

static NTSTATUS darwin_NtNotifyChangeKey( HANDLE a1, HANDLE a2, PIO_APC_ROUTINE a3, PVOID a4, PIO_STATUS_BLOCK a5, ULONG a6, BOOLEAN a7, PVOID a8, ULONG_PTR a9, ULONG_PTR a10 )
{
    return NtNotifyChangeKey( a1, a2, a3, a4, a5, a6, a7, a8, (ULONG)a9, (BOOLEAN)a10 );
}

static NTSTATUS darwin_NtNotifyChangeMultipleKeys( HANDLE a1, ULONG a2, OBJECT_ATTRIBUTES* a3, HANDLE a4, PIO_APC_ROUTINE a5, PVOID a6, PIO_STATUS_BLOCK a7, ULONG a8, ULONG_PTR a9, ULONG_PTR a10, ULONG_PTR a11, ULONG_PTR a12 )
{
    return NtNotifyChangeMultipleKeys( a1, a2, a3, a4, a5, a6, a7, a8, (BOOLEAN)a9, (PVOID)a10, (ULONG)a11, (BOOLEAN)a12 );
}

static NTSTATUS darwin_NtQueryEaFile( HANDLE a1, PIO_STATUS_BLOCK a2, PVOID a3, ULONG a4, BOOLEAN a5, PVOID a6, ULONG a7, PULONG a8, ULONG_PTR a9 )
{
    return NtQueryEaFile( a1, a2, a3, a4, a5, a6, a7, a8, (BOOLEAN)a9 );
}

static NTSTATUS darwin_NtSecureConnectPort( PHANDLE a1, PUNICODE_STRING a2, PSECURITY_QUALITY_OF_SERVICE a3, PLPC_SECTION_WRITE a4, PSID a5, PLPC_SECTION_READ a6, PULONG a7, PVOID a8, ULONG_PTR a9 )
{
    return NtSecureConnectPort( a1, a2, a3, a4, a5, a6, a7, a8, (PULONG)a9 );
}

static const struct { const char *name; void *func; } darwin_syscall_wrappers[] =
{
    { "NtReadFile", darwin_NtReadFile },
    { "NtDeviceIoControlFile", darwin_NtDeviceIoControlFile },
    { "NtWriteFile", darwin_NtWriteFile },
    { "NtWriteFileGather", darwin_NtWriteFileGather },
    { "NtMapViewOfSection", darwin_NtMapViewOfSection },
    { "NtAccessCheckAndAuditAlarm", darwin_NtAccessCheckAndAuditAlarm },
    { "NtReadFileScatter", darwin_NtReadFileScatter },
    { "NtQueryDirectoryFile", darwin_NtQueryDirectoryFile },
    { "NtFsControlFile", darwin_NtFsControlFile },
    { "NtCreateFile", darwin_NtCreateFile },
    { "NtAccessCheckByTypeAndAuditAlarm", darwin_NtAccessCheckByTypeAndAuditAlarm },
    { "NtCreateLowBoxToken", darwin_NtCreateLowBoxToken },
    { "NtCreateNamedPipeFile", darwin_NtCreateNamedPipeFile },
    { "NtCreateSectionEx", darwin_NtCreateSectionEx },
    { "NtCreateThreadEx", darwin_NtCreateThreadEx },
    { "NtCreateToken", darwin_NtCreateToken },
    { "NtCreateTransaction", darwin_NtCreateTransaction },
    { "NtCreateUserProcess", darwin_NtCreateUserProcess },
    { "NtLockFile", darwin_NtLockFile },
    { "NtMapViewOfSectionEx", darwin_NtMapViewOfSectionEx },
    { "NtNotifyChangeDirectoryFile", darwin_NtNotifyChangeDirectoryFile },
    { "NtNotifyChangeKey", darwin_NtNotifyChangeKey },
    { "NtNotifyChangeMultipleKeys", darwin_NtNotifyChangeMultipleKeys },
    { "NtQueryEaFile", darwin_NtQueryEaFile },
    { "NtSecureConnectPort", darwin_NtSecureConnectPort },
};
